const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d");
const state={layout:1,accent:"#9fded7",position:50,vertical:50,zoom:100,overlay:true,overlayStrength:70,headlineSize:78,headlineFont:"Playfair Display",textAlign:"left",letterSpacing:0,lineHeight:1.08,brightness:100,saturation:100,photo:null,logo:null,logoPosition:"top-right",logoSize:"medium",safeGuide:false,brand:"wanderland"};
const $=id=>document.getElementById(id),fields=["location","headline","subheadline","cta"];
const brands={wanderland:{accent:"#9fded7",overlay:70,bg:"#17323b",text:"#ffffff"},coastal:{accent:"#8fbfc0",overlay:48,bg:"#eaf0ee",text:"#16313a"},earth:{accent:"#d8b98a",overlay:58,bg:"#433a31",text:"#fffaf2"},mono:{accent:"#f0eee8",overlay:76,bg:"#151719",text:"#ffffff"}};
function wrap(text,maxWidth,font){ctx.font=font;const words=(text||"").trim().split(/\s+/),lines=[];let line="";for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width+Math.max(0,state.letterSpacing)*(test.length-1)>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines}
function drawTracked(text,x,y,maxWidth,font,color,lineHeight,maxLines=4,align=state.textAlign,spacing=state.letterSpacing){ctx.font=font;ctx.fillStyle=color;ctx.textBaseline="top";const lines=wrap(text,maxWidth,font).slice(0,maxLines),sizes=lines.map(line=>[...line].reduce((w,ch)=>w+ctx.measureText(ch).width,0)+spacing*Math.max(0,[...line].length-1));let anchor=x;if(align==="center")anchor=x+maxWidth/2;if(align==="right")anchor=x+maxWidth;lines.forEach((line,i)=>{let start=anchor;if(align==="center")start-=sizes[i]/2;if(align==="right")start-=sizes[i];let cursor=start;[...line].forEach(ch=>{ctx.fillText(ch,cursor,y+i*lineHeight);cursor+=ctx.measureText(ch).width+spacing})});ctx.textAlign="left";return lines.length}
function drawText(text,x,y,maxWidth,font,color,lineHeight,maxLines=4,align=state.textAlign){return drawTracked(text,x,y,maxWidth,font,color,lineHeight,maxLines,align,state.letterSpacing)}
function photoBox(x,y,w,h){ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();if(state.photo)drawImageCover(state.photo,x,y,w,h,state.position,state.vertical,state.zoom);else{const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,"#78929a");g.addColorStop(.5,"#42646e");g.addColorStop(1,"#102d38");ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.fillStyle="rgba(255,255,255,.55)";ctx.font="600 15px DM Sans";ctx.fillText("ADD YOUR TRAVEL PHOTO",x+30,y+h/2)}ctx.restore()}
function drawImageCover(img,x,y,w,h,pos,vpos,zoom){ctx.save();ctx.filter="brightness("+state.brightness+"%) saturate("+state.saturation+"%)";const r=Math.max(w/img.width,h/img.height)*(zoom/100),nw=img.width*r,nh=img.height*r,maxX=Math.max(0,nw-w),maxY=Math.max(0,nh-h);ctx.drawImage(img,x-maxX*pos/100,y-maxY*vpos/100,nw,nh);ctx.restore()}
function overlay(x,y,w,h){if(!state.overlay)return;const a=state.overlayStrength/100,g=ctx.createLinearGradient(x,y,x,y+h);g.addColorStop(0,"rgba(4,15,21,"+(a*.08)+")");g.addColorStop(.52,"rgba(4,15,21,"+(a*.12)+")");g.addColorStop(1,"rgba(4,15,21,"+(a*.88)+")");ctx.fillStyle=g;ctx.fillRect(x,y,w,h)}
function base(color="#eef0eb"){ctx.clearRect(0,0,1080,1350);ctx.fillStyle=color;ctx.fillRect(0,0,1080,1350)}
function logo(max){if(!state.logo)return;const r=Math.min(max/state.logo.width,max/state.logo.height),w=state.logo.width*r,h=state.logo.height*r,m=58;let x=1080-m-w,y=m;if(state.logoPosition==="top-left")x=m;if(state.logoPosition==="bottom-right")y=1350-m-h;if(state.logoPosition==="bottom-left"){x=m;y=1350-m-h}ctx.drawImage(state.logo,x,y,w,h)}
function label(text,x,y,color=state.accent){ctx.font="700 12px DM Sans";ctx.fillStyle=color;ctx.fillText((text||"").toUpperCase(),x,y)}
function line(x1,y1,x2,y2,color="#b8c3c0"){ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function headlineFont(){return '600 '+state.headlineSize+'px "'+state.headlineFont+'"'}
function logoMax(){return state.logoSize==="small"?70:state.logoSize==="large"?150:105}
function layout1(){base(brands[state.brand].bg);photoBox(0,0,1080,1350);overlay(0,0,1080,1350);label($(fields[0]).value,70,72);logo(logoMax());drawText($(fields[1]).value,70,850,890,headlineFont(),brands[state.brand].text,state.headlineSize*state.lineHeight,3);drawText($(fields[2]).value,72,1080,720,"400 24px DM Sans","#edf3f2",35,3);ctx.font="700 14px DM Sans";ctx.fillStyle=state.accent;ctx.fillText($(fields[3]).value.toUpperCase()+"  /  EXPLORE",72,1250)}
function layout2(){base("#e7ebe7");ctx.fillStyle="#d4ddd9";ctx.fillRect(34,34,1012,1282);photoBox(66,66,948,790);ctx.fillStyle="#f8f8f4";ctx.fillRect(66,856,948,394);label($(fields[0]).value,110,912,"#647b7c");drawText($(fields[1]).value,110,950,810,headlineFont(),"#14272f",state.headlineSize*state.lineHeight,2);drawText($(fields[2]).value,112,1096,690,"400 20px DM Sans","#596b70",29,3);line(112,1195,790,1195);ctx.font="700 11px DM Sans";ctx.fillStyle="#4f6d70";ctx.fillText($(fields[3]).value.toUpperCase(),112,1215);logo(logoMax())}
function layout3(){base("#f0eee8");label("FIELD NOTES / 01",70,68,"#27383d");line(70,92,1010,92);photoBox(70,138,570,700);drawText($(fields[1]).value,690,180,300,headlineFont(),"#18313a",state.headlineSize*.9*state.lineHeight,4);drawText($(fields[2]).value,692,430,280,"400 18px DM Sans","#5c6b6d",27,5);label($(fields[0]).value,692,690,"#718887");ctx.font='600 30px "Playfair Display"';ctx.fillStyle="#18313a";ctx.fillText($(fields[3]).value,70,950);line(70,980,1010,980);ctx.font="400 13px DM Sans";ctx.fillStyle="#738084";ctx.fillText("A visual note from the road.",70,1028);logo(logoMax())}
function layout4(){base("#122731");photoBox(510,0,570,1350);if(state.overlay)overlay(510,0,570,1350);label($(fields[0]).value,70,110);drawText($(fields[1]).value,68,420,380,headlineFont(),"#fff",state.headlineSize*state.lineHeight,4);drawText($(fields[2]).value,70,770,350,"400 20px DM Sans","#c9d7d9",29,5);ctx.font="700 12px DM Sans";ctx.fillStyle=state.accent;ctx.fillText($(fields[3]).value.toUpperCase()+"   →",70,1120);logo(logoMax())}
function layout5(){base("#f5f3ed");photoBox(80,72,920,690);label($(fields[0]).value,80,820,"#536b6d");drawText($(fields[1]).value,80,875,850,headlineFont(),"#14282f",state.headlineSize*state.lineHeight,3);drawText($(fields[2]).value,82,1082,650,"400 19px DM Sans","#5a696d",28,4);line(82,1200,1000,1200);ctx.font="700 11px DM Sans";ctx.fillStyle="#18313a";ctx.fillText($(fields[3]).value.toUpperCase(),82,1228);logo(logoMax())}
function layout6(){base("#dfe7e3");ctx.fillStyle="#f1f3ef";ctx.fillRect(44,44,992,1262);photoBox(70,70,940,760);ctx.fillStyle="#18333b";ctx.fillRect(70,830,940,400);ctx.fillStyle=state.accent;ctx.fillRect(70,830,8,400);label($(fields[0]).value,115,882);drawText($(fields[1]).value,115,930,790,headlineFont(),"#fff",state.headlineSize*state.lineHeight,3);drawText($(fields[2]).value,116,1100,680,"400 18px DM Sans","#d2dcdc",27,3);logo(logoMax());ctx.font="700 10px DM Sans";ctx.fillStyle="#18333b";ctx.fillText($(fields[3]).value.toUpperCase(),70,1270)}
const layouts={1:layout1,2:layout2,3:layout3,4:layout4,5:layout5,6:layout6};
function safeGuide(){if(!state.safeGuide)return;ctx.save();ctx.setLineDash([10,10]);ctx.strokeStyle="rgba(255,255,255,.5)";ctx.lineWidth=2;ctx.strokeRect(54,54,972,1242);ctx.strokeStyle="rgba(20,40,47,.32)";ctx.strokeRect(92,92,896,1166);ctx.restore()}
function render(showGuide=true){layouts[state.layout]();if(showGuide)safeGuide()}
fields.forEach(id=>$(id).addEventListener("input",render));
["position","vertical","zoom","overlayStrength","headlineSize","letterSpacing","lineHeight","brightness","saturation"].forEach(id=>$(id).addEventListener("input",e=>{state[id]=+e.target.value;const out=$(id+"Value");if(out)out.textContent=id==="headlineSize"?e.target.value+"px":id==="letterSpacing"?e.target.value+"px":id==="lineHeight"?e.target.value:id==="brightness"||id==="saturation"?e.target.value+"%":e.target.value+"%";render()}));
$("overlayToggle").addEventListener("change",e=>{state.overlay=e.target.checked;render()});$("headlineFont").addEventListener("change",e=>{state.headlineFont=e.target.value;render()});$("textAlign").addEventListener("change",e=>{state.textAlign=e.target.value;render()});$("logoPosition").addEventListener("change",e=>{state.logoPosition=e.target.value;render()});$("logoSize").addEventListener("change",e=>{state.logoSize=e.target.value;render()});$("safeGuide").addEventListener("change",e=>{state.safeGuide=e.target.checked;render()});
document.querySelectorAll(".layout").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".layout").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.layout=+b.dataset.layout;$("layoutName").textContent=b.querySelector("b").textContent+" / Editorial";render()}));
document.querySelectorAll(".swatches button").forEach(b=>b.addEventListener("click",()=>{state.accent=b.dataset.accent;document.querySelectorAll(".swatches button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");render()}));
document.querySelectorAll(".preset").forEach(b=>b.addEventListener("click",()=>{const p=JSON.parse(b.dataset.preset);state.accent=p.accent;state.overlayStrength=p.overlay;document.querySelectorAll(".preset").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const out=$("overlayStrengthValue");if(out)out.textContent=p.overlay+"%";render()}));
document.querySelectorAll(".brand-preset").forEach(b=>b.addEventListener("click",()=>{const p=brands[b.dataset.brand];state.brand=b.dataset.brand;state.accent=p.accent;state.overlayStrength=p.overlay;document.querySelectorAll(".brand-preset").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");const out=$("overlayStrengthValue");if(out)out.textContent=p.overlay+"%";render()}));
function loadImage(input,key){input.addEventListener("change",()=>{const f=input.files[0];if(!f)return;const img=new Image();img.onload=()=>{state[key]=img;render()};img.src=URL.createObjectURL(f)})}
loadImage($("photoInput"),"photo");loadImage($("logoInput"),"logo");
function exportPNG(){render(false);const a=document.createElement("a");a.download="travel-feed-"+Date.now()+".png";a.href=canvas.toDataURL("image/png");a.click();render()}
$("downloadTop").addEventListener("click",exportPNG);render();